### ISSUE TITLE
好奇这个弹幕功能实现的思路是什么

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [KurosakiRei/webpack-userscript-template-with-vue3#1]
自己看youtubu的时候就困扰没有弹幕很不习惯，看评论又看不到视频了。所以我通过改变页面布局把评论放到左侧实现了。假如我也可以用脚本实现弹幕感觉很酷，所以向哥哥请教一下

**Comment by KurosakiRei** [comment]
如果只是看youtube的话可以用chrome web store的插件: Dmooji, 功能就是把视频的评论全部换化成弹幕， 如果评论带时间，就会在相应的视频时间点出现，如果没有时间好像就是随机的。（其实不是很想给这个插件打广告，个人感觉没有很好用，我的理解是弹幕就应该在相应时间点出现才有意义）

我的那个脚本的功能是加载本地已有的xml弹幕文件（就跟你在某些文件处理网站上传本地文件一样），或者在线搜索视频平台的弹幕。

简单的实现思路大概是：检测网站是否存在H5播放器（包括网站里的iframe），有的话就注入弹幕功能，但弹幕功能不是我写的，用的是别人已经写好的开源弹幕引擎，你在可以google或者github搜一下`JS弹幕引擎`就可以搜到很多

PS: 其实还有问题的话可以在论坛里回复，主要是这个repository不是那个脚本的，是开发脚本的空模板
